### ISSUE TITLE
Think on Rest Endpoints

### ISSUE THREAD

**Issue by dan323** [dan323/price-comparator#8]

**Comment by byesfi** [comment]
`openapi: 3.0.0
info:
  title: Product Array API
  version: 1.0.0
  description: |
    This API provides an endpoint for retrieving an array of products.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /productsArray:
    get:
      summary: Get an array of products
      description: Retrieve an array of products.
      parameters:
        - name: limit
          in: query
          description: Maximum number of products to retrieve
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          examples:
            'application/json':
              - id: "1"
                name: "Product 1"
                description: "Description of product 1"
                price: 19.99
                quantity: 100
              - id: "2"
                name: "Product 2"
                description: "Description of product 2"
                price: 29.99
                quantity: 50

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "1"
        name:
          type: string
          example: Sample Product
        description:
          type: string
          example: This is a sample product
        price:
          type: number
          format: double
          example: 19.99
        quantity:
          type: integer
          example: 100
      required:
        - name
        - description
        - price
        - quantity
`

**Comment by byesfi** [comment]
openapi: 3.0.0
info:
  title: Product Array API
  version: 1.0.0
  description: |
    This API provides an endpoint for retrieving an array of products.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /productsArray:
    get:
      summary: Get an array of products
      description: Retrieve an array of products.
      parameters:
        - name: limit
          in: query
          description: Maximum number of products to retrieve
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          examples:
            'application/json':
              - id: "1"
                name: "Product 1"
                description: "Description of product 1"
                price: 19.99
                quantity: 100
              - id: "2"
                name: "Product 2"
                description: "Description of product 2"
                price: 29.99
                quantity: 50

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "1"
        name:
          type: string
          example: Sample Product
        description:
          type: string
          example: This is a sample product
        price:
          type: number
          format: double
          example: 19.99
        quantity:
          type: integer
          example: 100
      required:
        - name
        - description
        - price
        - quantity

**Comment by byesfi** [comment]
```
openapi: 3.0.0
info:
  title: Price Comparison API
  version: 1.0.0
  description: |
    This API provides endpoints for retrieving price comparison data based on product EAN.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /products/{productId}/price-comparison:
    parameters:
      - name: productId
        in: path
        required: true
        description: ID of the product to retrieve price comparison data for
        schema:
          type: string
      - name: ean
        in: query
        required: true
        description: EAN (European Article Number) of the product
        schema:
          type: string
    get:
      summary: Get price comparison data
      description: Retrieve price comparison data for a specific product based on its EAN.
      responses:
        '200':
          description: Price comparison data
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    shop:
                      type: string
                      example: Shop A
                    price:
                      type: number
                      format: double
                      example: 19.99
        '404':
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "1"
        name:
          type: string
          example: Sample Product
        description:
          type: string
          example: This is a sample product
        ean:
          type: string
          example: 1234567890123
        price:
          type: number
          format: double
          example: 19.99
      required:
        - name
        - description
        - ean
        - price

```
